apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: prometheus-operator-grafana-test
  labels:
    app: grafana
    chart: grafana-3.5.7
    heritage: Tiller
    release: prometheus-operator
spec:
  allowPrivilegeEscalation: true
  privileged: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - secret
